### ISSUE TITLE
Increase Readability of Block Toggle

### ISSUE THREAD

**Issue by yamamara** [SmartyNotchy/PHS-10th-SMCS-Blocking#1]
With the current implementation, the button to toggle blocks is confusing because of the fact that there isn't a clear indication on which block is currently being displayed.

A possible change could be making two separate buttons for block X and block Y, and use different colors to distinguish which block is being displayed.

Possible code:
`<button id="block_x">Block X</button>`
`<button id="block_y">Block Y</button>`

**Comment by pilliamw** [comment]
![image](https://github.com/user-attachments/assets/15dcc39f-feca-462e-a783-89592d5c441e)

Thanks for the feature suggestion :D
