### ISSUE TITLE
Background not Rendering Correctly on Mobile Devices

### ISSUE THREAD

**Issue by yamamara** [SmartyNotchy/PHS-10th-SMCS-Blocking#2]
Issue: The background is different on computer and mobile devices. The computer renders it as the correct image, while on phone it's a different gradient.

Steps to Reproduce:
1. Load website on mobile device
2. Look at website background

**Comment by pilliamw** [comment]
This appears to be an issue only on Safari iOS. I just pushed a change that hopefully should fix it.

Can you check right now to see if the issue still persists?

**Comment by yamamara** [comment]
The issue has been resolved!
